'use strict';
const $ = id => document.getElementById(id);
let selected = null, current = null, state = null, tab = 'summary', busy = false, lastContent = '';
let importFile = null, modelCatalogKey = '', modelOptionsKey = '', modelMeetingId = null, executionDefault = null;
const labels = {done:'Terminé',queued:'En attente',preparing:'Préparation',transcribing:'Transcription',summarizing:'Résumé en cours',recording:'Enregistrement',error:'À vérifier',cancelled:'Annulé',interrupted:'Interrompu'};
const running = s => ['queued','preparing','transcribing','summarizing'].includes(s);
const date = t => new Date(t*1000).toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});
const time = sec => { sec=Math.max(0,Math.floor(sec));return [Math.floor(sec/3600),Math.floor(sec/60)%60,sec%60].map(x=>String(x).padStart(2,'0')).join(':'); };
function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function toast(message,error=false){$('toast').textContent=message;$('toast').className=error?'error':'';$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,error?9000:3500);}
async function api(path,method='GET',data){const res=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json','X-Clair-Token':window.CLAIR_TOKEN},body:data===undefined?undefined:JSON.stringify(data)});let value;try{value=await res.json();}catch{throw new Error('Réponse inattendue du service local.');}if(!res.ok)throw new Error(typeof value.detail==='string'?value.detail:'La demande n’a pas pu aboutir.');return value;}
async function action(fn){if(busy)return;busy=true;try{await fn();await refresh();}catch(e){toast(e.message,true);}finally{busy=false;}}
function view(name){for(const v of ['home','record','meeting','models'])$(v+'-view').hidden=v!==name;$('nav-home').classList.toggle('active',name==='home'||name==='meeting');$('nav-record').classList.toggle('active',name==='record');$('nav-models').classList.toggle('active',name==='models');if(name!=='meeting'){selected=null;current=null;lastContent='';}window.scrollTo(0,0);}
function badge(status){return node('span','status-badge'+(running(status)||status==='recording'?' busy':['error','interrupted','cancelled'].includes(status)?' error':''),labels[status]||status);}
const gigabytes = n => (n/1e9).toLocaleString('fr-FR',{maximumFractionDigits:2})+' Go';
function modelOptions(select, preferred){const old=preferred||select.value;select.replaceChildren();for(const m of state.catalog.models.filter(m=>m.installed)){const o=node('option','',m.name);o.value=m.id;select.append(o);}if(!select.options.length){const o=node('option','','Installez un modèle dans le catalogue');o.value='';select.append(o);}select.value=[...select.options].some(o=>o.value===old)?old:state.catalog.default;if(select.selectedIndex<0)select.selectedIndex=0;}
function updateModels(){if(!state?.catalog)return;const c=state.catalog;const optionsKey=JSON.stringify([c.default,c.models.map(m=>[m.id,m.installed])]);if(modelOptionsKey!==optionsKey){modelOptionsKey=optionsKey;for(const id of ['import-model','record-model','summary-model'])modelOptions($(id));}if(executionDefault!==c.execution){executionDefault=c.execution;for(const id of ['import-execution','record-execution','default-execution'])$(id).value=c.execution;}const key=JSON.stringify(c);if(key===modelCatalogKey)return;modelCatalogKey=key;const grid=$('models-grid');grid.replaceChildren();const download=c.download,downloading=download&&['downloading','verifying'].includes(download.status);$('model-download').hidden=!download;if(download){const m=c.models.find(x=>x.id===download.model_id);$('model-download-message').textContent=(m?m.name+' · ':'')+download.message;$('model-download-fill').style.width=Math.min(100,download.progress)+'%';$('model-download-size').textContent=gigabytes(download.received)+' / '+gigabytes(download.total);$('cancel-download').hidden=!downloading;}for(const m of c.models){const preferred=m.id===c.default;const card=node('article','model-card'+(preferred?' preferred':''));const top=node('div','model-tags');top.append(node('span','',preferred?'Par défaut':m.installed?'Installé':'À télécharger'),node('span','',new Date(m.release_date+'T12:00:00').toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'})));card.append(top,node('h2','',m.name),node('p','',m.description));const tags=node('div','model-tags');tags.append(node('span','',gigabytes(m.size)),node('span','',m.quantization),node('span','','Mémoire ≈ '+m.memory_gb+' Go'));card.append(tags);const row=node('div','model-actions'),b=node('button',m.installed?'secondary':'primary',m.installed?(preferred?'Modèle par défaut':'Utiliser par défaut'):(downloading&&download.model_id===m.id?'En cours…':m.partial_bytes?'Reprendre le téléchargement':'Télécharger'));b.disabled=m.installed?preferred:!!downloading;b.onclick=()=>action(async()=>{if(m.installed){await api('models/'+m.id+'/default','POST',{});for(const id of ['import-model','record-model'])if(!$(id).disabled)$(id).value=m.id;toast('Modèle par défaut enregistré.');}else await api('models/'+m.id+'/download','POST',{});});const a=node('a','','Fiche du modèle ↗');a.href=m.source;a.target='_blank';a.rel='noopener noreferrer';row.append(b,a);card.append(row);grid.append(card);}}
function updateMeetingModel(m){const locked=!!state.active||state.recording.active;$('summary-model').disabled=locked;$('summary-execution').disabled=locked;if(modelMeetingId!==m.id){modelMeetingId=m.id;modelOptions($('summary-model'),m.llm_model);$('summary-execution').value=m.execution||'auto';}const model=m.report?.model?.name||state.catalog.models.find(x=>x.id===m.report_model)?.name||(m.report?'Qwen2.5 14B Instruct (version précédente)':'');$('report-model').textContent=model?'Compte rendu actuel : '+model+(m.summary_device?' · '+m.summary_device.toUpperCase():''):'';}
function renderLibrary(){const lib=$('library'),history=$('history');lib.replaceChildren();history.replaceChildren();const meetings=state.meetings;$('meeting-count').textContent=meetings.length+' réunion'+(meetings.length>1?'s':'');if(!meetings.length){lib.append(node('div','empty','Vos prochains comptes rendus vous attendront ici.'));}meetings.forEach((m,i)=>{const row=node('button','library-row');row.append(node('div','file-icon','▤'));const title=node('div','row-title');title.append(node('strong','',m.title),node('small','',date(m.created)+(m.duration?' · '+Math.ceil(m.duration/60)+' min':'')));row.append(title,badge(m.status),node('span','row-arrow','↗'));row.onclick=()=>m.status==='recording'?showRecord():openMeeting(m.id);lib.append(row);if(i<8){const h=node('button','history-item');h.append(node('strong','',m.title),node('small','',date(m.created)));h.onclick=row.onclick;history.append(h);}});}
async function refresh(){try{state=await api('state');renderLibrary();updateModels();updateCapture();$('show-import').disabled=!!state.active||state.recording.active;$('start-record').disabled=!!state.active||state.recording.active;if(selected){const m=await api('meetings/'+selected);renderMeeting(m);}}catch(e){if(!$('toast').hidden)return;toast('Le service local ne répond plus. Relancez Clair si nécessaire.',true);}}
async function showRecord(){view('record');try{const d=await api('devices');const sys=$('system-device'),mic=$('mic-device');sys.replaceChildren();mic.replaceChildren();for(const x of d.system){const o=node('option','',x.name.replace(' [Loopback]',''));o.value=x.id;sys.append(o);}for(const x of d.microphones){const o=node('option','',x.name);o.value=x.id;mic.append(o);}const none=node('option','','Sans microphone');none.value='';mic.append(none);if(d.default_system!==null)sys.value=d.default_system;if(d.default_mic!==null)mic.value=d.default_mic;if(!d.system.length)toast('Aucune sortie audio compatible détectée. Branchez un casque ou des haut-parleurs.',true);updateCapture();}catch(e){toast(e.message,true);}}
function updateCapture(){if(!state)return;const r=state.recording;$('record-state').textContent=r.active?'Enregistrement en cours':'Prêt à enregistrer';$('record-indicator').classList.toggle('live',r.active);$('record-timer').textContent=time(r.seconds);$('system-level').style.width=Math.round(r.levels.system*100)+'%';$('mic-level').style.width=Math.round(r.levels.mic*100)+'%';$('start-record').hidden=r.active;$('stop-record').hidden=!r.active;for(const id of ['record-title','system-device','mic-device','record-language','record-context','record-model','record-execution'])$(id).disabled=r.active;$('record-warning').textContent=!r.healthy?'Une source audio s’est arrêtée. Arrêtez et vérifiez vos périphériques.':r.errors.length?'Des interruptions audio ont été signalées. Vérifiez l’enregistrement.':'Les indicateurs s’animent lorsque du son est capturé.';}
async function openMeeting(id){view('meeting');selected=id;modelMeetingId=null;tab='summary';lastContent='';$('audio').pause();$('audio').removeAttribute('src');await refresh();}
function seek(ts){const audio=$('audio');if(!audio.src)return;audio.currentTime=typeof ts==='number'?ts:ts.split(':').reduce((a,b)=>a*60+Number(b),0);audio.play().catch(()=>{});}
function evidence(n,quote){if(quote)n.title='Extrait original : '+quote;return n;}
function timeButton(ts){const b=node('button','time-link',typeof ts==='number'?time(ts):ts);b.onclick=()=>seek(ts);return b;}
function empty(container,title,text){const p=node('div','placeholder');p.append(node('strong','',title),node('span','',text));container.append(p);}
function renderMeeting(m){current=m;updateMeetingModel(m);$('meeting-title').textContent=m.title;$('meeting-date').textContent=date(m.created).toUpperCase();$('meeting-meta').textContent=(m.duration?Math.ceil(m.duration/60)+' minutes · ':'')+(m.device==='cuda'?'Transcription GPU NVIDIA · ':m.device==='cpu'?'Transcription CPU · ':'')+'Conservé sur votre PC';const b=badge(m.status);$('detail-status').className=b.className;$('detail-status').textContent=b.textContent;const isRunning=running(m.status);$('progress-panel').hidden=!isRunning;$('progress-message').textContent=m.message;$('progress-fill').style.width=m.progress+'%';$('cancel-job').disabled=state.active!==m.id;$('generate-summary').disabled=!m.segments.length||!!state.active||state.recording.active;$('generate-summary').textContent=m.report?'✦ Refaire le résumé':'✦ Générer le résumé';$('segment-count').textContent=m.segments.length;$('error-panel').hidden=!['error','interrupted','cancelled'].includes(m.status);if(!$('error-panel').hidden){$('error-panel').replaceChildren(node('div','',m.message));const retry=node('button','secondary','Relancer la transcription');retry.disabled=!!state.active||state.recording.active;retry.onclick=()=>action(()=>api('meetings/'+m.id+'/retry','POST',{summary_only:false}));$('error-panel').append(retry);}
const audio=$('audio'),source=location.origin+'/api/meetings/'+m.id+'/audio';if(m.duration&&audio.src!==source){audio.src=source;audio.load();}document.querySelector('.audio-panel').hidden=!m.duration;
const key=JSON.stringify([m.id,m.report,m.segments.length,m.status]);if(key!==lastContent){lastContent=key;renderSummary(m);renderTranscript();}setTab(tab);}
function renderSummary(m){const c=$('summary-content');c.replaceChildren();if(!m.report){empty(c,running(m.status)?'L’essentiel prend forme.':'Votre compte rendu apparaîtra ici.',running(m.status)?'Vous pouvez déjà consulter la transcription pendant le traitement.':'Générez un résumé à partir de la transcription disponible.');return;}const r=m.report;const overview=node('div','summary-overview');overview.append(node('div','eyebrow','EN QUELQUES MOTS'),node('p','',r.overview));c.append(overview);if(r.topics?.length){const topics=node('div','summary-grid');r.topics.forEach(t=>{const panel=node('section','summary-section');panel.append(node('h2','',t.title));t.points.forEach(p=>panel.append(node('p','decision-item','• '+p)));topics.append(panel);});c.append(topics);}const grid=node('div','summary-grid'),decisions=node('section','summary-section'),questions=node('section','summary-section');decisions.append(node('h2','','Décisions prises'));if(!r.decisions.length)decisions.append(node('p','input-note','Aucune décision explicite identifiée.'));r.decisions.forEach(d=>{const row=node('div','decision-item'),text=node('div','',d.text);if(d.time)text.append(evidence(timeButton(d.time),d.quote));row.append(node('span','check-icon','✓'),text);decisions.append(row);});questions.append(node('h2','','Questions ouvertes'));if(!r.questions.length)questions.append(node('p','input-note','Aucune question ouverte identifiée.'));r.questions.forEach(q=>questions.append(node('p','decision-item','↳ '+q)));grid.append(decisions,questions);c.append(grid);if(r.proposals?.length){const proposals=node('section','summary-section');proposals.append(node('h2','','Propositions à confirmer'));r.proposals.forEach(d=>{const row=node('p','decision-item',d.text);if(d.time)row.append(evidence(timeButton(d.time),d.quote));proposals.append(row);});c.append(proposals);}const actions=node('section','summary-section');actions.append(node('h2','','Prochaines étapes'));if(!r.actions.length)actions.append(node('p','input-note','Aucune action explicite identifiée.'));else{const table=node('table','action-table'),head=node('tr','');['ACTION','RESPONSABLE','ÉCHÉANCE','REPÈRE'].forEach(x=>head.append(node('th','',x)));const thead=node('thead','');thead.append(head);table.append(thead);const body=node('tbody','');r.actions.forEach(a=>{const row=node('tr','');[a.task,a.owner,a.due].forEach(x=>row.append(node('td','',x)));const t=node('td','');if(a.time)t.append(evidence(timeButton(a.time),a.quote));else t.textContent='—';row.append(t);body.append(row);});table.append(body);actions.append(table);}c.append(actions);if(m.capture_warnings?.length)c.append(node('p','summary-note','La capture a signalé des interruptions audio. Vérifiez les passages concernés.'));c.append(node('p','summary-note','Compte rendu généré par IA. Vérifiez les décisions, noms, chiffres et attributions dans la transcription. Les repères permettent de réécouter les passages cités.'));}
function renderTranscript(){if(!current)return;const list=$('transcript-list');list.replaceChildren();const query=$('transcript-search').value.toLocaleLowerCase('fr');const segments=current.segments.filter(s=>s.text.toLocaleLowerCase('fr').includes(query));if(!segments.length){empty(list,current.segments.length?'Aucun passage trouvé.':'La transcription apparaîtra ici.',current.segments.length?'Essayez un autre mot.':'Les premiers passages seront disponibles pendant le traitement.');return;}segments.forEach(s=>{const row=node('div','transcript-row');row.append(timeButton(s.start),node('p','',s.text));list.append(row);});}
function setTab(value){tab=value;$('summary-content').hidden=value!=='summary';$('transcript-content').hidden=value!=='transcript';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===value));}
function summaryText(r){return [r.title,'',r.overview,'',...(r.topics||[]).flatMap(t=>[t.title,...t.points.map(p=>'• '+p),'']),'PROPOSITIONS À CONFIRMER',...(r.proposals||[]).map(d=>'• '+d.text),'','DÉCISIONS',...r.decisions.map(d=>'• '+d.text),'','ACTIONS',...r.actions.map(a=>'• '+a.task+' — '+a.owner+' — '+a.due),'','QUESTIONS OUVERTES',...r.questions.map(q=>'• '+q)].join('\n');}
$('nav-home').onclick=()=>view('home');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>view('home'));$('nav-models').onclick=()=>view('models');$('nav-record').onclick=showRecord;$('show-record').onclick=showRecord;
$('show-import').onclick=()=>{updateModels();$('import-dialog').showModal();$('import-path').focus();};$('close-import').onclick=()=>$('import-dialog').close();$('import-dialog').onclick=e=>{if(e.target===$('import-dialog')&&!$('import-submit').disabled){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('choose-file').onclick=()=>$('import-file').click();
$('import-file').onchange=()=>{const file=$('import-file').files[0];if(!file)return;importFile=file;$('import-path').value=file.name;$('import-path').setCustomValidity('');$('import-progress').hidden=true;};
$('import-path').oninput=()=>{importFile=null;$('import-file').value='';};
$('import-dialog').addEventListener('cancel',e=>{if($('import-submit').disabled)e.preventDefault();});
function uploadFile(file,metadata){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();const p=$('import-progress');p.hidden=false;p.textContent='Copie du fichier sur votre PC…';xhr.open('POST','/api/import-upload?'+new URLSearchParams({...metadata,filename:file.name}));xhr.setRequestHeader('X-Clair-Token',window.CLAIR_TOKEN);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.upload.onprogress=e=>{p.textContent=e.lengthComputable?'Copie locale du fichier : '+Math.round(e.loaded/e.total*100)+' %':'Copie du fichier sur votre PC…';};xhr.upload.onload=()=>{p.textContent='Fichier copié. Préparation de la transcription…';};xhr.onload=()=>{let value;try{value=JSON.parse(xhr.responseText);}catch{reject(new Error('Réponse inattendue du service local.'));return;}if(xhr.status>=200&&xhr.status<300)resolve(value);else reject(new Error(typeof value.detail==='string'?value.detail:'L’import du fichier n’a pas pu aboutir.'));};xhr.onerror=()=>reject(new Error('La copie a été interrompue. Vérifiez que Clair est ouvert et réessayez.'));xhr.onabort=()=>reject(new Error('Copie annulée.'));xhr.send(file);});}
$('import-form').onsubmit=e=>{e.preventDefault();action(async()=>{const b=$('import-submit'),original=b.textContent;const controls=[...$('import-form').querySelectorAll('input,select,textarea,button')];controls.forEach(c=>c.disabled=true);b.textContent='Import en cours…';try{const metadata={title:$('import-title').value,language:$('import-language').value,context:$('import-context').value,llm_model:$('import-model').value,execution:$('import-execution').value,auto_summary:$('import-mode').value==='summary'};const m=importFile?await uploadFile(importFile,metadata):await api('import','POST',{...metadata,path:$('import-path').value});$('import-dialog').close();importFile=null;$('import-file').value='';$('import-path').value='';await openMeeting(m.id);}finally{controls.forEach(c=>c.disabled=false);b.textContent=original;$('import-progress').hidden=true;}});};
$('start-record').onclick=()=>action(async()=>{await api('record/start','POST',{title:$('record-title').value,system_id:$('system-device').value?Number($('system-device').value):null,mic_id:$('mic-device').value?Number($('mic-device').value):null,language:$('record-language').value,context:$('record-context').value,llm_model:$('record-model').value,execution:$('record-execution').value});toast('Enregistrement démarré. Gardez Clair ouvert.');});
$('stop-record').onclick=()=>action(async()=>{const m=await api('record/stop','POST',{});await openMeeting(m.id);});
$('cancel-job').onclick=()=>action(()=>api('meetings/'+selected+'/cancel','POST',{}));$('generate-summary').onclick=()=>action(()=>api('meetings/'+selected+'/retry','POST',{summary_only:true,llm_model:$('summary-model').value,execution:$('summary-execution').value}));$('transcript-search').oninput=renderTranscript;
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
$('export-select').onchange=async e=>{const name=e.target.value;e.target.value='';if(!name||!selected)return;if(name.startsWith('compte-rendu')&&!current.report){toast('Le compte rendu n’est pas encore disponible.',true);return;}try{const res=await fetch('/api/meetings/'+selected+'/export/'+name);if(!res.ok)throw new Error('Cet export n’est pas encore disponible.');const url=URL.createObjectURL(await res.blob());const a=node('a','');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}catch(e){toast(e.message,true);}};
$('copy-content').onclick=async()=>{if(!current)return;const text=tab==='summary'?(current.report?summaryText(current.report):''):current.segments.map(s=>'['+time(s.start)+'] '+s.text).join('\n');if(!text){toast('Le contenu n’est pas encore disponible.',true);return;}try{await navigator.clipboard.writeText(text);toast('Copié dans le presse-papiers.');}catch{toast('Le navigateur n’autorise pas la copie. Utilisez l’export.',true);}};
$('open-folder').onclick=()=>action(()=>api('folder','POST',{}));$('quit').onclick=()=>action(async()=>{await api('shutdown','POST',{});clearInterval(poll);toast('Clair est fermé. Vous pouvez fermer cet onglet.');});
const poll=setInterval(refresh,2000);refresh();
$('cancel-download').onclick=()=>action(()=>api('models/download/cancel','POST',{}));
$('default-execution').onchange=()=>action(()=>api('preferences','POST',{execution:$('default-execution').value}));
